### ISSUE TITLE
DisplayPort-5 ( IE display port N°02 on rear panel ) not detected

### ISSUE THREAD

**Issue by GEPLinux** [IGEL-Community/IGEL-Docs#8]
Hi,
On my IGEL with double display port & IGEL OS 11.06 : 
**ISSUE :** DisplayPort-5 ( IE display port N°02 on rear panel ) not detected 
**ON STARTING UP :**
My Display primary was OK : as DisplayPort-3 ( IE display port N°01 on rear panel ) detected ( --output DisplayPort-3 --mode 1920x1200 --primary everything perfect ...)  But my Display 'right-of DisplayPort-3' was OFF : as DisplayPort-5 not detected by IGEL OS (_Screenshot-01 : GIT_IGL-01__20220427_221228.png_)
**USING XRANDR**
DisplayPort-5 ( & DisplayPort-6 ) are detected again, Then Second Screen ON again eith all previous setting kept.. ( --output DisplayPort-5 --mode 1920x1200 --right-of DisplayPort-3 … as usual )
( _Screenshot-02 : GIT_IGL-02_20220427_221319.png_ )
**Q1_** Is it a common & known issue ? If Yes : 
**Q1-1_** Will IGEL OS 11.07 fix it ? 
**Q1-2_** Is there antoter kiss solution tio this issue ? 
**Q2_** Can we use xrandr bash shell script on start up to set manually the displays ?
Thanks for your help, Best Regards,
**GEPLinux**
![GIT_IGL-01__20220427_221228](https://user-images.githubusercontent.com/96615531/165624622-43e8cf93-53e3-49d4-8ba8-10fb67660d16.png)
![GIT_IGL-02_20220427_221319](https://user-images.githubusercontent.com/96615531/165624838-4d04e9f4-4301-4f1d-a9dd-94f454a7a9b1.png)

**Comment by rneher-igel** [comment]
Hello,
Please post your question in IGEL Community on Slack (#igel-os) channel.

**Comment by GEPLinux** [comment]
ok

**Comment by falkheiland** [comment]
hi @GEPLinux !
this is not a the place for troubleshooting specific IGELOS related problems.
Please head over and join the [IGEL Community Slack](http://slack.igelcommunity.com/) and post your question in the #igel-os channel!
