### ISSUE TITLE
IGEL OS 11.07 Kernel 5.15 ( Jammy Jellyfish 22.04 ) on ( Bionic Beaver 18.04 ) DE...

### ISSUE THREAD

**Issue by GEPLinux** [IGEL-Community/IGEL-Docs#9]
IGEL OS 11.07  PRETTY_NAME still **Bionic Beaver 18.04** on top of **Kernel 5.15**...
Seems odd is it true & ok ?
BR

**Comment by rneher-igel** [comment]
IGEL OS 11 is IGEL's own version of Linux. Most libraries come from Ubuntu 18.04.

**Comment by GEPLinux** [comment]
Thanks la lot for the answer then we can consider that future upgrades will keep 18.04 librairies and we don't have to wait for DE upgrade, 
Quasi a rolling release ...
Best regards
GEPLinux

**Comment by falkheiland** [comment]
@GEPLinux the issues here are not the (prefered) place to ask generic IGEL-related questions. 
For those cases, please consider joining the IGEL Community Slack https://www.igelcommunity.com/
